### ISSUE TITLE
Background of tile as transparent

### ISSUE THREAD

**Issue by marceloandrioni** [baagaard-usgs/cartopy-extra-tiles#2]
Hello, first of all, thanks for the awesome code, it's been really useful. My question is if there is any way of using a transparent background when requesting a tile. I am trying to load a layer that only has labels over a cartopy feature. Checking the [preview](http://maps.stamen.com/toner-labels/#9/37.7816/-122.2531) I would assume the white would show as transparent in python, but it shows as black. I tried passing a `trasparent=True` or `alpha=0` but it didn't work. Do you have any suggestions?

Thank you!

```
import matplotlib.pyplot as plt
import cartopy
import cartopy.crs as ccrs

extent = [-123, -121.5, 37, 38.5]
fig, ax = plt.subplots(1, 1, subplot_kw={'projection': ccrs.PlateCarree()})

ax.set_extent([-123, -121.5, 37, 38.5])
ax.add_feature(cartopy.feature.LAND)

tiler = CachedTiler(Stamen(style='terrain-labels'), cache_dir="/tmp")
ax.add_image(tiler, 8)
plt.show()
```

![labels](https://user-images.githubusercontent.com/13545615/84533203-06702d00-acbe-11ea-889a-29197bfd6dd9.png)

matplotlib.__version__ '3.2.1'
cartopy.__version__ '0.18.0'

**Comment by baagaard-usgs** [comment]
Pass `desired_tile_form="RGBA"` as an argument to the Stamen constructor. The desired tile form is the PIL image mode (L, RGB, RGBA, CMYK, HSV, I, F). For example, you can change the terrain images to grayscale by using the I mode in combination with `cmap="gray"` to `add_image`.

## Transparent images with labels
```
tiler = CachedTiler(Stamen(desired_tile_form="RGBA", style="terrain-labels"), cache_dir="./tiles")
ax.set_extent([-123, -121.5, 37, 38.5])
ax.add_image(tiler, 8)
```

## Grayscale terrain
```
tiler = CachedTiler(Stamen(desired_tile_form="L", style="terrain"), cache_dir="./tiles")
ax.set_extent([-123, -121.5, 37, 38.5])
ax.add_image(tilerBg, 8, cmap="gray")
```

**Comment by marceloandrioni** [comment]
Thanks, with the `desired_tile_form="RGBA"` kw it worked perfectly.

![map_stamen](https://user-images.githubusercontent.com/13545615/84579867-1106f100-ada8-11ea-82ed-a64796d459e2.png)
